---
- name: install nfs-common
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: install locales-all
  ansible.builtin.package:
    name: locales-all
    state: present

- name: ensure LANG=C.UTF-8 (24h format)
  shell: update-locale LANG=C.UTF-8
  args:
    executable: /bin/bash

# todo find out how to configure this to run after a vm resume

- name: install chrony
  ansible.builtin.package:
    name: chrony
    state: present

# we need this to enable the agent -  https://www.snel.com/support/nstall-qemu-guest-agent-for-debian-ubuntu/
# qm create --agent=1 # https://pve.proxmox.com/pve-docs/qm.1.html

- name: install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: enable service qemu-guest-agent and ensure it is not masked
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    masked: no

- name: start qemu-guest-agent
  ansible.builtin.systemd:
    state: started
    name: qemu-guest-agent

- name: start chrony
  ansible.builtin.systemd:
    state: started
    name: chrony
