collections:
  - name: community.general
  # - name: kubernetes.core
  - name: community.hrobot # for hetzner
  #- name: ansible.posix
  #- name: ansible.utils

  # - name: https://github.com/egandro/k3s-ansible.git
  #   type: git
  #   version: galaxy
