---
- name: read public SSH key
  set_fact:
    id_rsa_pub: "{{ lookup('file', ansible_helper_ssh_key_file_pub) }}"

- name: add authorized_key for '{{ ansible_helper_ssh_key_for_user }}' user
  ansible.posix.authorized_key:
    user: "{{ ansible_helper_ssh_key_for_user }}"
    key: "{{ id_rsa_pub }}"
    state: present

- name: add public ssh key to "{{ ansible_helper_ssh_key_for_user }}"
  shell: |
    if [ "{{ ansible_helper_ssh_key_for_user }}" = "root" ]; then
        HOME_DIR=/root
    else
        HOME_DIR=/home/"{{ ansible_helper_ssh_key_for_user }}"
    fi
    mkdir -p "${HOME_DIR}"/.ssh
    chmod 700 "${HOME_DIR}"/.ssh
    chown "{{ ansible_helper_ssh_key_for_user }}":"{{ ansible_helper_ssh_key_for_user }}" "${HOME_DIR}"/.ssh

    echo "{{ id_rsa_pub }}" > "${HOME_DIR}"/.ssh/id_rsa.pub
    chown "{{ ansible_helper_ssh_key_for_user }}":"{{ ansible_helper_ssh_key_for_user }}" "${HOME_DIR}"/.ssh/id_rsa.pub
    chmod 600 "${HOME_DIR}"/.ssh/id_rsa.pub
  args:
    executable: /bin/bash
