---
# os_helper_hostname: testian
# os_helper_domain: example.com
# os_helper_ip4: 1.2.3.4
# os_helper_netmask4: 255.255.255.0
# os_helper_gateway4: 4.5.6.7
# os_helper_dns: 8.8.8.8
# os_helper_ip6prefix: de:ad:ba # prefix is optional - if exist we add ip6
# os_helper_ip6: de:ad:ba:b:e # if there is no prefix, we just add the ipv6
# os_helper_route4: 'up route add -net 167.235.1.128 netmask 255.255.255.192 gw 167.235.1.129 dev' '{{ ansible_default_ipv4.interface }} will be added'
# os_helper_device: <default use the device that ansible detects>

# optional
# os_helper_wifi_name: My Wifi
# os_helper_wifi_password: 0123456789
