---

- name: install sudo
  ansible.builtin.package:
    name: sudo
    state: present

- name: make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: allow 'wheel' group to have password less sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: create '{{ ansible_helper_ansible_new_user }}' user in sudoers group
  ansible.builtin.user:
    name: "{{ ansible_helper_ansible_new_user }}"
    shell: /bin/bash
    groups: wheel
    append: yes

- name: read public SSH key
  set_fact:
    id_rsa_pub: "{{ lookup('file', ansible_helper_ssh_key_file_pub) }}"

- name: add authorized_key for '{{ ansible_helper_ansible_new_user }}' user
  ansible.posix.authorized_key:
    user: "{{ ansible_helper_ansible_new_user }}"
    key: "{{ id_rsa_pub }}"
    state: present
