---
# hetzner_robot_server_reinstall:
#   id: 123456789
#   robot_admin_user: '#123456789+abcde' # send via mail after generating the admin pw
#   robot_admin_pw: 'very secret' # create with pwgen 32
#   ssh_key_file_pub: ' ~/.ssh/id_rsa.pub'
#   ip4: 1.2.3.4
#   distribution: 'Debian 12 base'
#   locked: true # optional - if set, don't allow reinstall
