---

- name: create new ansible ssh secrets file
  connection: local
  become: false
  shell: |
    KEY_FILE="{{ ansible_helper_server_ssh_keys_ssh_key_file }}"
    SECRETS_ENC_FILE="{{ ansible_helper_server_ssh_keys_ssh_secrets_enc_file }}"

    rm -f "${SECRETS_ENC_FILE}"
    touch "${SECRETS_ENC_FILE}"
    chmod 600 "${SECRETS_ENC_FILE}"

    echo -n "server_ssh_key: " > "${SECRETS_ENC_FILE}"
    cat "${KEY_FILE}" | base64 -w0  >> "${SECRETS_ENC_FILE}"
    echo ""  >> "${SECRETS_ENC_FILE}"
    echo ""  >> "${SECRETS_ENC_FILE}"

    echo -n "server_ssh_key_pub: "  >> "${SECRETS_ENC_FILE}"
    cat "${KEY_FILE}.pub" | base64 -w0  >> "${SECRETS_ENC_FILE}"
    echo ""  >> "${SECRETS_ENC_FILE}"
    echo ""  >> "${SECRETS_ENC_FILE}"
  args:
    executable: /bin/bash

- name: encrypt ansible ssh secrets file
  connection: local
  become: false
  shell: |
    export ANSIBLE_VAULT_PASSWORD_FILE="{{ ansible_helper_server_ssh_keys_ssh_ansible_vault_file }}"
    SECRETS_ENC_FILE="{{ ansible_helper_server_ssh_keys_ssh_secrets_enc_file }}"

    ansible-vault encrypt "${SECRETS_ENC_FILE}"
  args:
    executable: /bin/bash
