---
# - name: wait until apt process finishes
#   wait_for:
#     path: /var/lib/dpkg/lock-frontend
#     state: absent
#     delay: 5
#     timeout: 300

- name: wait until apt process finishes
  shell: |
    while ! pgrep apt ; (($?)) ;do
        sleep 10
    done
  args:
    executable: /bin/bash
