---

- name: check if systemd-resolved is installed
  ansible.builtin.package_facts:
    manager: auto

- name: disable systemd-resolved if installed
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when: "'systemd-resolved' in ansible_facts.packages"

# - name: remove systemd-resolved
#   ansible.builtin.package:
#     name: systemd-resolved
#     state: present

- name: installing /etc/resolv.conf
  ansible.builtin.template:
    src:  templates/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
